site_name: 岚天方块窝
site_url: https://mc.ltya.top
repo_name: mcxiaolan/mc-nest
repo_url: https://github.com/mcxiaolan/mc-nest
nav:
  - index.md
  - 服务器:
    - 岚风集: server/index.md
    - 加入服务器: server/join.md
    - 服务器状态: server/status.md
    - 封禁名单: server/banlist.md
  - 互通服:
    - 互通服: server-je/index.md
    - 加入服务器: server-je/join.md
    - 服务器状态: server-je/status.md
  - 资源推荐: 
    - recommend/index.md
  - 自定义披风模板: 
    - 自定义披风模板: skin_packs/index.md
    - Custom 改法（推荐）: skin_packs/custom-template.md 
    - Persona 改法: skin_packs/skin-pack-template.md
  - 联系我们: contact.md
  - 支持我们: donate.md


theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy

plugins:
  - tags
  - search
  - blog:
      blog_dir: recommend
      post_url_format: "{slug}"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#extra_css:
#  - assets/stylesheets/extra.css
